source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'sqlite3'
gem 'jbuilder', '~> 2.0'
gem 'devise', '3.5.2'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end
